--- gst-plugins-base-0.10.30/common/gtk-doc.mak~	2010-03-30 21:34:17.000000000 +0200
+++ gst-plugins-base-0.10.30/common/gtk-doc.mak	2010-08-24 21:29:28.851390752 +0200
@@ -232,6 +232,6 @@
 	-cp $(srcdir)/$(DOC_MODULE).types $(distdir)/
 	-cp $(srcdir)/$(DOC_MODULE)-sections.txt $(distdir)/
 	cd $(distdir) && rm -f $(DISTCLEANFILES)
-        -gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
+	gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
 
 .PHONY : dist-hook-local docs
--- gst-plugins-base-0.10.30/common/gtk-doc-plugins.mak~	2010-07-04 17:34:06.000000000 +0200
+++ gst-plugins-base-0.10.30/common/gtk-doc-plugins.mak	2010-08-24 21:35:25.370507605 +0200
@@ -332,7 +332,7 @@
 	-cp $(srcdir)/$(DOC_MODULE).types $(distdir)/
 	-cp $(srcdir)/$(DOC_MODULE)-sections.txt $(distdir)/
 	cd $(distdir) && rm -f $(DISTCLEANFILES)
-        -gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
+	gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
 
 .PHONY : dist-hook-local docs
 
